version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://symfony:symfony@db:3306/symfony
    volumes:
      - .:/usr/src/app
    networks:
      - symfony_network

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sym64Rami
      MYSQL_USER: root
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - symfony_network

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony_network

volumes:
  db_data:

networks:
  symfony_network:
